### ISSUE TITLE
Gallery Doesn't Work

### ISSUE THREAD

**Issue by simonpmiles** [bigspring/M3#20]
Check css and js files are included

**Comment by simonpmiles** [comment]
DEV NOTE: Clearing isn't included in Foundation6 but will be in 6.2 so we will need to look for another solution to this for the time being.

http://stackoverflow.com/questions/34665604/clearing-lightbox-is-not-in-foundation-6-so-what-is-the-alternative

**Comment by dmseaton** [comment]
FoundationPress doesn't appear to handle the gallery at all, either because it is eventually coming to Foundation or by virtue of no longer being in Foundation.

[FrescoJS](http://frescojs.com) looks like a suitable replacement for Clearing. We'll need to look into incorporating this or a similar library as per the old FP way.

F6 has been out for long enough that it might be assumed that they don't intend to replace Clearing. We should consider any replacement a long-term measure unless there is information to the contrary.

**Comment by harrybigspring** [comment]
http://frescojs.com/ is the only option I can find that does what we want. I've tested it on our mobile devices and it works fine. It does have a price of $95 for an unlimited licence.
